### ISSUE TITLE
bug: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by firminochangani** [codebytesfl/Clean-Comments#1]
Hi @codebytesfl, great work, I love the premise of this extension. 

I tried to use it on VS Code 1.48.2 and I had the following error:

![Screenshot 2020-09-09 at 20 31 52](https://user-images.githubusercontent.com/1679333/92644784-c7ad3b80-f2db-11ea-9051-939656fbd871.png)

**Comment by codebytesfl** [comment]
> Hi @codebytesfl, great work, I love the premise of this extension.
> 
> I tried to use it on VS Code 1.48.2 and I had the following error:
> 
> ![Screenshot 2020-09-09 at 20 31 52](https://user-images.githubusercontent.com/1679333/92644784-c7ad3b80-f2db-11ea-9051-939656fbd871.png)

Thank you! I will take a look at this,

Is there any other type of information you can share as to what led to this? Some things that could help find this bug faster!
- Language selected
- Was the document empty
- Were you at the beginning of the line, end of the line
- Does this happen all the time in your document, or only when you try to use the command at a specific spot in the document.

Thank you for reporting this :)

**Comment by firminochangani** [comment]
- I tried with an empty document;
- The document was empty;
- I was at the beginning of the line;
- All the time;
